[package]
name = "bspl"
version = "0.1.0"
authors = ["Ansley Peduru <ansleypeduru96@gmail.com>"]
repository = "https://github.com/apeduru/bspl.git"
readme = "README.md"
description = "A REPL for pracitising bit-wise operations"

[dependencies]
rustyline = "1.0.0"
tempfile = "2.1.4"
